import type { BacktestReport } from '../../../../shared/backtest';
export const metrics = {
  totalReturn: 0.1,
  annualizedReturn: 0.05,
  maxDrawdown: {
    pct: 0.08,
    peakDate: '2020-01-01',
    troughDate: '2020-02-01',
    recoveryDate: null,
    durationDays: 31,
  },
  sharpe: 1.2,
  sharpeInfinite: null,
  profitFactor: 2,
  profitFactorInfinite: false,
  winRate: 0.5,
  expectancy: 10,
  maxLosingStreak: 2,
  tradeCount: 21,
  winningTrades: 11,
  losingTrades: 10,
  grossProfit: 200,
  grossLoss: 100,
} as const;
const range = { startDate: '2020-01-01', endDate: '2020-12-31' };
export const report: BacktestReport = {
  id: 7,
  strategyId: 1,
  version: 1,
  kind: 'completo',
  dataSource: 'simulated',
  providerId: 'simulated',
  totalReturn: 0.1,
  maxDrawdownPct: 0.08,
  sharpe: 1.2,
  tradeCount: 21,
  durationMs: 100,
  createdAt: '2021-01-01T00:00:00Z',
  config: {
    desde: '2020-01-01',
    hasta: '2022-12-31',
    ejecutadoHasta: '2021-12-31',
    markets: ['SPY'],
    initialCash: 10000,
    riskPerTrade: 0.01,
    maxPositions: 5,
    parameters: { fast: 20, slow: 50 },
    warmupSessions: 200,
    split: { train: 0.6, validation: 0.2, test: 0.2 },
    walkForward: {},
    sensitivity: { xParam: 'fast', yParam: 'slow' },
    monteCarlo: { seed: 1, simulations: 1000, method: 'permutation' },
  },
  costs: { commissionPct: 0.05, commissionMin: 1, slippageBps: 5, spreadBps: 2 },
  split: {
    train: range,
    validation: range,
    test: range,
    counts: { train: 150, validation: 50, test: 50 },
    sessionCount: 250,
  },
  metrics,
  equityCurve: [
    { date: '2020-01-01', equity: 10000, cash: 10000, positions: 0 },
    { date: '2020-12-31', equity: 11000, cash: 11000, positions: 0 },
  ],
  benchmark: {
    ticker: 'SPY',
    totalReturn: 0.2,
    curve: [{ date: '2020-01-01', equity: 10000, cash: 10000, positions: 0 }],
  },
  trades: Array.from({ length: 21 }, (_, i) => ({
    ticker: `T${i}`,
    signalDate: '2020-01-01',
    entryDate: '2020-01-02',
    exitDate: '2020-02-01',
    entryPrice: 100,
    exitPrice: 110,
    shares: 1,
    commission: 2,
    slippage: 1,
    grossPnl: 10,
    pnl: 8,
    exitReason: 'signal',
  })),
  walkForward: {
    objective: 'sharpe',
    trainSize: 126,
    testSize: 63,
    step: 63,
    windows: [
      {
        index: 0,
        train: range,
        test: range,
        params: { fast: 20 },
        inSampleMetric: 1.2,
        inSampleMetrics: metrics,
        outOfSampleMetric: 0.5,
        outOfSampleMetrics: metrics,
        candidates: 4,
      },
    ],
    meanInSampleMetric: 1.2,
    meanOutOfSampleMetric: 0.5,
    outOfSampleTrades: 21,
  },
  sensitivity: {
    metric: 'sharpe',
    xParam: 'fast',
    xValues: [20, 30],
    yParam: 'slow',
    yValues: [50],
    cells: [[1.2, null]],
    baseCell: { x: 0, y: 0 },
    baseValue: 1.2,
  },
  monteCarlo: {
    method: 'permutation',
    seed: 1,
    simulations: 1000,
    tradeCount: 21,
    initialCash: 10000,
    returnPercentiles: { p5: 0.1, p50: 0.1, p95: 0.1 },
    drawdownPercentiles: { p5: 0.02, p50: 0.05, p95: 0.1 },
    distribution: [
      { totalReturn: 0.1, maxDrawdown: 0.02 },
      { totalReturn: 0.1, maxDrawdown: 0.1 },
    ],
  },
  warnings: [
    {
      rule: 'sesgo-supervivencia',
      severity: 'method',
      message: 'El universo puede excluir activos desaparecidos.',
    },
  ],
  finalTest: { status: 'disponible', runId: null, executedAt: null },
};
