import type {
  Signal,
  PaperPortfolioOverview,
  SignalStrategyState,
} from '../../../../shared/signals';
import type { JournalEntry } from '../../../../shared/journal';
export const signal: Signal = {
  id: 1,
  ticker: 'AAPL',
  direction: 'largo',
  entry: 100,
  stop: 95,
  target: 115,
  confidence: 0.78,
  reason: 'Cierre sobre la media de 50 sesiones con volumen confirmado.',
  strategies: [
    {
      strategyId: 1,
      name: 'Tendencia SMA',
      version: 3,
      direction: 'largo',
      confidence: 0.78,
      reason: 'Cruce alcista',
    },
  ],
  dataUsed: {
    barDate: '2026-10-08',
    desde: '2025-10-08',
    hasta: '2026-10-08',
    barCount: 252,
    batchId: 1,
    batchVersion: 2,
    source: 'simulado',
  },
  decision: {
    status: 'aprobada',
    size: 25,
    sizeFactor: 1,
    riskAmount: 125,
    notional: 2500,
    reasons: [],
    decidedAt: '2026-10-09T13:42:00Z',
  },
  createdAt: '2026-10-09T13:42:00Z',
};
export const portfolio: PaperPortfolioOverview = {
  equity: 10000,
  currency: 'USD',
  positions: [
    {
      id: 1,
      ticker: 'AAPL',
      direction: 'largo',
      size: 25,
      entry: 100,
      markPrice: 102,
      pnl: 50,
      pnlPct: 2,
      sector: 'Tecnología',
      currency: 'USD',
      signalId: 1,
      openedAt: signal.createdAt,
    },
  ],
  drawdownPct: 3.2,
  drawdownLimitPct: 10,
  dailyLossPct: 0,
  dailyLossLimitPct: 2,
  exposureByAsset: [{ key: 'AAPL', notional: 2550, pct: 25.5, limitPct: 30 }],
  exposureBySector: [{ key: 'Tecnología', notional: 2550, pct: 25.5, limitPct: 30 }],
  openPositions: 1,
  maxOpenPositions: 5,
  updatedAt: signal.createdAt,
};
export const strategies: SignalStrategyState[] = [
  {
    strategyId: 1,
    name: 'Tendencia SMA',
    version: 3,
    status: 'activa',
    lastBarDate: '2026-10-08',
    lastEvaluatedAt: signal.createdAt,
    lastOutcome: 'senal',
    lastSignalId: 1,
  },
  {
    strategyId: 2,
    name: 'Reversión RSI',
    version: 2,
    status: 'paper',
    lastBarDate: '2026-10-08',
    lastEvaluatedAt: signal.createdAt,
    lastOutcome: 'sin-senal',
    lastSignalId: null,
  },
];
export const contradiction: JournalEntry = {
  id: 3,
  type: 'contradiccion',
  createdAt: '2026-10-09T13:21:00Z',
  ticker: 'MSFT',
  strategies: [
    { strategyId: 1, name: 'Tendencia SMA', version: 3 },
    { strategyId: 2, name: 'Reversión RSI', version: 2 },
  ],
  reason: 'Propuestas enfrentadas: Tendencia SMA compra y Reversión RSI venta.',
  dataUsed: null,
  result: 'sin-senal',
  errors: [],
  ruleChecks: [],
  signalId: null,
};
